######################################################################
# Automatically generated by qmake (3.0) Sat May 30 22:32:53 2015
######################################################################

LIBS += -L/usr/local/lib \
-lopencv_core \
-lopencv_imgproc \
-lopencv_highgui \
-lopencv_video
CONFIG += c++11
greaterThan(QT_MAJOR_VERSION,4): QT += widgets

TEMPLATE = app
TARGET = SubZero
INCLUDEPATH += . \
               SubZero/src/util \
               SubZero/src/view \
               SubZero/test/util/filter \
               SubZero/src/util/filter \
               SubZero/src/util/data \
               SubZero/src \
               SubZero/src/model \
               SubZero/src/model/interface \
               SubZero/src/model/state \
               SubZero/test/util \
               SubZero/src/controller/command \
               SubZero/src/controller/task \
               SubZero/src/controller/controllers \
               SubZero/test/util/data \
               SubZero/test \
                /usr/local/include/opencv


# Input
HEADERS += SubZero/src/Observable.h \
           SubZero/src/Observer.h \
           SubZero/src/SubZero.h \
           SubZero/src/SubZeroFactory.h \
           SubZero/src/model/CameraModel.h \
           SubZero/src/model/FPGAModel.h \
           SubZero/src/model/Model.h \
           SubZero/src/util/IDHasher.h \
           SubZero/src/util/Logger.h \
           SubZero/src/util/StringTools.h \
           SubZero/src/util/Timer.h \
           SubZero/src/util/Util.h \
           SubZero/src/view/guiview.h \
           SubZero/src/view/menu.h \
           SubZero/src/view/observer.h \
           SubZero/src/view/view.h \
           SubZero/test/util/IDHasherTEST.h \
           SubZero/src/controller/command/Command.h \
           SubZero/src/controller/command/CommandFactory.h \
           SubZero/src/controller/controllers/Controller.h \
           SubZero/src/controller/controllers/ControllerThread.h \
           SubZero/src/controller/task/BaseTask.h \
           SubZero/src/controller/task/TaskA.h \
           SubZero/src/controller/task/TaskFactory.h \
           SubZero/src/model/interface/CameraInterface.h \
           SubZero/src/model/interface/FPGAInterface.h \
           SubZero/src/model/interface/HwInterface.h \
           SubZero/src/model/state/CameraState.h \
           SubZero/src/model/state/FPGAState.h \
           SubZero/src/model/state/State.h \
           SubZero/src/util/data/Data.h \
           SubZero/src/util/data/DataFactory.h \
           SubZero/src/util/data/FPGAData.h \
           SubZero/src/util/data/ImgData.h \
           SubZero/src/util/filter/Filter.h \
           SubZero/src/util/filter/FilterFactory.h \
           SubZero/src/util/filter/FilterManager.h \
           SubZero/src/util/filter/NullFPGAFilter.h \
           SubZero/src/util/filter/NullImgFilter.h \
           SubZero/src/util/filter/RGBFilter.h \
           SubZero/src/util/filter/TemplateFilter.h \
           SubZero/test/util/data/DataTEST.h \
           SubZero/test/util/data/FPGADataTEST.h \
           SubZero/test/util/data/ImgDataTEST.h \
           SubZero/test/util/filter/FilterManagerTEST.h \
           SubZero/test/CollectionTEST.h

SOURCES += SubZero/src/Main.cpp \
           SubZero/src/Observable.cpp \
           SubZero/src/Observer.cpp \
           SubZero/src/SubZero.cpp \
           SubZero/src/SubZeroFactory.cpp \
           SubZero/src/model/CameraModel.cpp \
           SubZero/src/model/FPGAModel.cpp \
           SubZero/src/model/Model.cpp \
           SubZero/src/util/IDHasher.cpp \
           SubZero/src/util/Logger.cpp \
           SubZero/src/util/StringTools.cpp \
           SubZero/src/util/Timer.cpp \
           SubZero/src/util/Util.cpp \
           SubZero/src/view/guiview.cpp \
           SubZero/src/view/menu.cpp \
           SubZero/src/view/observer.cpp \
           SubZero/src/view/view.cpp \
           SubZero/test/util/IDHasherTEST.cpp \
           SubZero/src/controller/command/Command.cpp \
           SubZero/src/controller/controllers/Controller.cpp \
           SubZero/src/controller/controllers/ControllerThread.cpp \
           SubZero/src/controller/task/BaseTask.cpp \
           SubZero/src/controller/task/TaskA.cpp \
           SubZero/src/controller/task/TaskFactory.cpp \
           SubZero/src/model/interface/CameraInterface.cpp \
           SubZero/src/model/interface/FPGAInterface.cpp \
           SubZero/src/model/interface/HwInterface.cpp \
           SubZero/src/model/state/CameraState.cpp \
           SubZero/src/model/state/FPGAState.cpp \
           SubZero/src/model/state/State.cpp \
           SubZero/src/util/data/Data.cpp \
           SubZero/src/util/data/DataFactory.cpp \
           SubZero/src/util/data/FPGAData.cpp \
           SubZero/src/util/data/ImgData.cpp \
           SubZero/src/util/filter/Filter.cpp \
           SubZero/src/util/filter/FilterFactory.cpp \
           SubZero/src/util/filter/FilterManager.cpp \
           SubZero/src/util/filter/NullFPGAFilter.cpp \
           SubZero/src/util/filter/NullImgFilter.cpp \
           SubZero/src/util/filter/RGBFilter.cpp \
           SubZero/src/util/filter/TemplateFilter.cpp \
           SubZero/test/util/data/DataTEST.cpp \
           SubZero/test/util/data/FPGADataTEST.cpp \
           SubZero/test/util/data/ImgDataTEST.cpp \
           SubZero/test/util/filter/FilterManagerTEST.cpp \
           SubZero/test/CollectionTEST.cpp
