# Project demo makefile
#
# Created by: Victor Zhang
#
# This makefile is included by each project demo
#
# You should only have to specify PROJ in each makefile
# and include this makefile
#

all:
	quartus_sh --flow compile $(PROJ)

clean:
	rm -rf *.rpt *.summary db incremental_db *.pin *.sof *.bak *.done

dl_hw:
	nios2-configure-sof || nios2-configure-sof

.PHONY: all clean dl_hw
